title: Spotify Project
#tagline:          A short tagline
#description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
url: http://lyannaliu.github.io

# Owner/author information
owner:
  name:           Spotify
  avatar:         Spotify.JPG
#  bio:
 


# Links to include in top navigation
# For external links add external: true
links:
  - title: Motivation and Abstract
    url: /
  - title: Description of Data
    url: /Description of Data/
  - title: Models and Methods
    url: /Models and Methods/
  - title: Results and Conclusion  
    url: /Results and Conclusion/
  - title: Appendix  
    url: /Appendix/
    



theme: jekyll-theme-minimal
